#!/usr/bin/env -S uv run python
"""piastra FEM compartment comparison: is the forward model limitation
due to skull modeling or something more fundamental?

compares 3/4/5-compartment FEM transfer matrices for 3 subjects.
the transfer matrices map stimulation dipoles to iEEG electrode potentials.
we compare predicted vs actual iEEG responses across compartment levels.

if 5c >> 3c: skull conductivity modeling is the bottleneck
if 5c ≈ 3c: the limitation is more fundamental
"""
from __future__ import annotations

import json
import sys
from datetime import UTC, datetime
from pathlib import Path

import numpy as np
from scipy.io import loadmat

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from eeg_cleaner.io_utils import timestamped_artifact_dir

PIASTRA_ROOT = PROJECT_ROOT / "data" / "external" / "piastra_2024" / "archive"
SUBJECTS = {"s0": "sub-s1", "s3": "sub-s2", "s4": "sub-s3"}  # model ID -> BIDS ID
COMPARTMENTS = [3, 4, 5]


def load_transfer_matrix(subject_model_id: str, n_compartments: int) -> np.ndarray:
    path = PIASTRA_ROOT / "output_python" / f"sol_tm_{subject_model_id}_{n_compartments}c.npy"
    # these .npy files were generated by the dataset authors' pipeline and contain
    # only numeric arrays (transfer matrices), not arbitrary objects
    return np.load(path, allow_pickle=False)


def load_dipole_data(subject_model_id: str) -> tuple[np.ndarray, np.ndarray]:
    pos = loadmat(str(PIASTRA_ROOT / "input_python" / f"dipole_pos_{subject_model_id}.mat"))
    ori = loadmat(str(PIASTRA_ROOT / "input_python" / f"dipole_ori_{subject_model_id}.mat"))
    # extract the array from the mat dict (key is variable name)
    pos_arr = next(v for k, v in pos.items() if not k.startswith("__"))
    ori_arr = next(v for k, v in ori.items() if not k.startswith("__"))
    return pos_arr.astype(np.float64), ori_arr.astype(np.float64)


def load_electrode_positions(subject_model_id: str) -> np.ndarray:
    mat = loadmat(str(PIASTRA_ROOT / "input_python" / f"elec_{subject_model_id}.mat"))
    elec = next(v for k, v in mat.items() if not k.startswith("__"))
    # may be a struct with 'pnt' or 'elecpos' field, or just a matrix
    if hasattr(elec, 'dtype') and elec.dtype.names:
        for field in ['pnt', 'elecpos', 'chanpos']:
            if field in elec.dtype.names:
                return elec[field][0, 0].astype(np.float64)
    return elec.astype(np.float64)


def load_conductivities(n_compartments: int) -> np.ndarray:
    path = PIASTRA_ROOT / "input_python" / f"cond{n_compartments}c.cnd"
    return np.loadtxt(path)


def corrcoef(a: np.ndarray, b: np.ndarray) -> float:
    if np.std(a) == 0 or np.std(b) == 0:
        return float("nan")
    return float(np.corrcoef(a, b)[0, 1])


def compare_compartments(subject_model_id: str) -> dict:
    """compare 3c/4c/5c transfer matrices for one subject."""
    dipole_pos, dipole_ori = load_dipole_data(subject_model_id)
    n_dipoles = dipole_pos.shape[0]

    transfer_matrices = {}
    for nc in COMPARTMENTS:
        tm = load_transfer_matrix(subject_model_id, nc)
        transfer_matrices[nc] = tm

    # compare each pair of compartment models
    pairwise_corrs = {}
    for i, nc1 in enumerate(COMPARTMENTS):
        for nc2 in COMPARTMENTS[i+1:]:
            tm1 = transfer_matrices[nc1]
            tm2 = transfer_matrices[nc2]
            per_dipole_corrs = []
            for d in range(n_dipoles):
                c = corrcoef(tm1[d], tm2[d])
                per_dipole_corrs.append(c)
            pairwise_corrs[f"{nc1}c_vs_{nc2}c"] = {
                "mean_corr": float(np.nanmean(per_dipole_corrs)),
                "median_corr": float(np.nanmedian(per_dipole_corrs)),
                "min_corr": float(np.nanmin(per_dipole_corrs)),
                "max_corr": float(np.nanmax(per_dipole_corrs)),
            }

    # compute norms for each compartment
    norm_stats = {}
    for nc in COMPARTMENTS:
        tm = transfer_matrices[nc]
        norms = np.linalg.norm(tm, axis=1)
        norm_stats[f"{nc}c"] = {
            "mean_norm": float(np.mean(norms)),
            "std_norm": float(np.std(norms)),
        }

    # relative difference between compartment models
    rel_diffs = {}
    for nc1, nc2 in [(3, 4), (4, 5), (3, 5)]:
        tm1 = transfer_matrices[nc1]
        tm2 = transfer_matrices[nc2]
        per_dipole_rel_diff = []
        for d in range(n_dipoles):
            denom = max(np.linalg.norm(tm1[d]), np.linalg.norm(tm2[d]), 1e-20)
            rel = np.linalg.norm(tm1[d] - tm2[d]) / denom
            per_dipole_rel_diff.append(float(rel))
        rel_diffs[f"{nc1}c_to_{nc2}c"] = {
            "mean_rel_diff": float(np.mean(per_dipole_rel_diff)),
            "max_rel_diff": float(np.max(per_dipole_rel_diff)),
        }

    return {
        "subject_model_id": subject_model_id,
        "n_dipoles": n_dipoles,
        "n_electrodes": transfer_matrices[3].shape[1],
        "pairwise_topography_correlation": pairwise_corrs,
        "pattern_norms": norm_stats,
        "relative_differences": rel_diffs,
    }


def main() -> None:
    output_dir = timestamped_artifact_dir("piastra_fem_comparison")
    output_dir.mkdir(parents=True, exist_ok=True)

    all_results = []
    for model_id, bids_id in SUBJECTS.items():
        print(f"  {model_id} ({bids_id})...", flush=True)
        try:
            result = compare_compartments(model_id)
            all_results.append(result)

            for pair, stats in result["pairwise_topography_correlation"].items():
                print(f"    {pair}: corr={stats['mean_corr']:.4f} "
                      f"(min={stats['min_corr']:.4f}, max={stats['max_corr']:.4f})", flush=True)
            for pair, stats in result["relative_differences"].items():
                print(f"    {pair}: mean_rel_diff={stats['mean_rel_diff']:.4f}", flush=True)
        except Exception as exc:
            print(f"    FAILED: {exc}", flush=True)
            all_results.append({"subject_model_id": model_id, "error": repr(exc)})

    # aggregate across subjects
    agg_pairwise = {}
    for pair_name in ["3c_vs_4c", "4c_vs_5c", "3c_vs_5c"]:
        corrs = [r["pairwise_topography_correlation"][pair_name]["mean_corr"]
                 for r in all_results if "pairwise_topography_correlation" in r]
        if corrs:
            agg_pairwise[pair_name] = {"grand_mean_corr": float(np.mean(corrs))}

    agg_rel_diffs = {}
    for pair_name in ["3c_to_4c", "4c_to_5c", "3c_to_5c"]:
        diffs = [r["relative_differences"][pair_name]["mean_rel_diff"]
                 for r in all_results if "relative_differences" in r]
        if diffs:
            agg_rel_diffs[pair_name] = {"grand_mean_rel_diff": float(np.mean(diffs))}

    summary = {
        "subject_count": len(all_results),
        "compartments_compared": COMPARTMENTS,
        "aggregate_pairwise_correlation": agg_pairwise,
        "aggregate_relative_differences": agg_rel_diffs,
        "completed_at_utc": datetime.now(UTC).isoformat(),
        "interpretation": (
            "if 3c_vs_5c correlation is very high (>0.95) and relative difference is small (<0.1), "
            "then adding compartments (CSF, white matter distinction) makes little difference, "
            "meaning the forward model limitation is NOT about skull modeling."
        ),
    }

    (output_dir / "subject_results.json").write_text(json.dumps(all_results, indent=2), encoding="utf-8")
    (output_dir / "batch_summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print(f"\nResults: {output_dir}")
    print(f"\nAggregate pairwise correlation:")
    for pair, stats in agg_pairwise.items():
        print(f"  {pair}: grand_mean={stats['grand_mean_corr']:.4f}")
    print(f"\nAggregate relative differences:")
    for pair, stats in agg_rel_diffs.items():
        print(f"  {pair}: grand_mean={stats['grand_mean_rel_diff']:.4f}")


if __name__ == "__main__":
    main()
